feat: do service classes, handlers, new errors, and new functions
Sardiand/java-filmorate pull request #8
Opened 2023-05-31 17:28 UTC by Sardiand

2023-05-31 19:48 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-05-31 19:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotExistsException.java
> +public class FilmNotExistsException extends RuntimeException {
Не нужно добавлять по классу на каждую сущность.
Исключения должны быть общими.
По одному для каждого кода ошибки который мы собираемся возвращать клиенту.
Например:
BadRequestException - кидаемся им, когда в процессе валидации нашли невалидное поле.
И потом обрабатываем как 400 HTTP статус код.
NotFoundException - кидаемся им, когда не нашли сущность по какому либо параметру, чаще всего по id.
Обрабатываем как 404 HTTP статус код.

2023-05-31 19:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @Size(max = 200, message = "Field \"description\" cannot contain more than 200 symbols.")
200 символов мало для описания, давай дадим больше...

2023-05-31 19:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private long id = 1L;
Идентификатор должен присваивать не сервис, а хранилище.

2023-05-31 19:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.addFilm(film);
Перед тем как добавить фильм не хотим проверить, а не существует ли уже такой же?

2023-05-31 19:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.updateFilm(film);
Проверку что фильм существует нужно делать в сервисе. 
А у тебя эта логика ушла в хранилище. Сервисы получились совсем пустыми, хотя это основная единица.

2023-05-31 19:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film deleteFilm(long id) {
Этот метод никто не вызывает, он нужен?

2023-05-31 19:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getFilms().containsKey(id)) {
Не правильно брать у хранилища все фильмы и искать есть ли среди них что то.
Правильно будет из хранилища выставить метод `Optional<Film> findById(long id)` который и будет отдавай искомый фильм!

2023-05-31 19:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isBlank() || user.getName().isEmpty()) {
Это наша бизнес логика и она должна быть в сервисе.

2023-05-31 19:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    void updateFilm(Film film);
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `filmService.addFilm()`

Получается масло-масляное! 

Лучше: `filmService.create()` `filmService.update()`

2023-06-04 12:02 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotExistsException.java
> +public class FilmNotExistsException extends RuntimeException {
Уменьшил количество исключений, сделал на 3 HTTP статус кода, а также оставил на исключение на параметры, так как там возвращается иная сущность в хэндлере.

2023-06-04 12:02 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @Size(max = 200, message = "Field \"description\" cannot contain more than 200 symbols.")
Тесты постмана рассчитаны на 200 символов в описании, поэтому оставил.

2023-06-04 12:02 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private long id = 1L;
Исправил.

2023-06-04 12:05 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.addFilm(film);
Добавил проверку.

2023-06-04 12:05 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.updateFilm(film);
Исправил.

2023-06-04 12:06 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film deleteFilm(long id) {
Добавил в контроллер вызов метода.

2023-06-04 12:06 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getFilms().containsKey(id)) {
Исправил.

2023-06-04 12:06 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isBlank() || user.getName().isEmpty()) {
Исправил.

2023-06-04 12:06 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    void updateFilm(Film film);
Исправил.

2023-06-04 17:17 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-04 17:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new IncorrectParameterException("count");
Это тоже частный случай `BadRequest` 
IncorrectParameterException - стоило полностью удалить

2023-06-04 17:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new BadRequestException("This film have already been added.");
Это тоже связано с тестами? 
В этом случае стоит кидать 409 код ошибки, и на это должно быть свое исключение.

2023-06-04 17:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getId() == null || filmStorage.getById(film.getId()).isEmpty()) {
То что фильм имеет id стоило бы проверить в контроллере это же валидация - зона ответственности контроллера.

2023-06-04 17:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            NotFoundException exception = new NotFoundException("There is no such film in database or field \"id\" is empty.");
Ну и полноценно пользуемся тем что у нас Optional

```
    public Film update(Film film) {
        filmStorage.getById(film.getId())
                   .orElseThrow(() -> new NotFoundException("Not found film by id: " + film.getId()));

        filmStorage.update(film);
        
        return film;
    }
```

Вот так это должно выглядеть через метод orElseThrow.
Соответственно проведи рефакторинг во всем приложении.

2023-06-04 17:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getName() == null || user.getName().isBlank() || user.getName().isEmpty()) {
Код с логикой имени, написан дважды.
При создании и обновлении.

2023-06-10 12:49 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new IncorrectParameterException("count");
Исправил.

2023-06-10 12:58 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new BadRequestException("This film have already been added.");
Исправил.

2023-06-10 15:17 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getName() == null || user.getName().isBlank() || user.getName().isEmpty()) {
Исправил, добавил метод по проверке и установке имени  в классе User.

2023-06-10 15:21 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            NotFoundException exception = new NotFoundException("There is no such film in database or field \"id\" is empty.");
Скорректировал, реализовал это в методе getById, чтобы везде не дублировать.

2023-06-10 15:21 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getId() == null || filmStorage.getById(film.getId()).isEmpty()) {
Исправил.

2023-06-10 19:26 UTC, FanaticFiz approved these changes

2023-06-10 19:26 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            BadRequestException exception = new BadRequestException("Field \"id\" of Film can't be null.");
Кстати, ты прав когда и логируешь ошибку и кидаешь исключение, но надо вынести сообщение в переменную и код станет аккуратнее

```
            String msg = "Field \"id\" of Film can't be null";
            log.error("Error: " + msg);
            throw new BadRequestException(msg);
```

2023-06-10 19:26 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmList.sort(Comparator.comparing(film -> film.getLikes().size(), Comparator.reverseOrder()));
Не правильно делать сортировку в сервисе.
Нужно в хранилище. Сейчас будет переход к базе данных и это уже ляжет на плечи SQL запросов.

2023-06-11 11:09 UTC, merged